-- V28__create_report_snapshots.sql
-- Audit GAP-039 (SRS 15.12 Business Rules: "historical reports are immutable
-- snapshots (regenerating a past-dated report reproduces the same figures
-- using point-in-time data)").
--
-- Every generated period report (on request or by the weekly scheduler) is
-- stored here as the exact JSON the recipient received. A request for a period
-- that has already ended is answered from the stored snapshot instead of being
-- recomputed. Rows are written once and never updated or deleted by the
-- application (the JPA entity is @Immutable).
--
-- department_id NULL = jurisdiction-wide report (Admin / Super Admin).
-- generated_by NULL  = generated by the scheduler.

CREATE TABLE report_snapshots (
    snapshot_id        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    report_type        VARCHAR(20)     NOT NULL,
    period_start       DATE            NOT NULL,
    period_end         DATE            NOT NULL,
    time_zone          VARCHAR(40)     NOT NULL,
    department_id      BIGINT UNSIGNED NULL,
    generated_by       BIGINT UNSIGNED NULL,
    generated_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    insufficient_data  BOOLEAN         NOT NULL,
    payload_json       JSON            NOT NULL,

    CONSTRAINT fk_report_snapshots_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_report_snapshots_generated_by
        FOREIGN KEY (generated_by) REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT chk_report_snapshots_type CHECK (report_type IN ('DAILY', 'WEEKLY', 'CUSTOM')),
    CONSTRAINT chk_report_snapshots_period CHECK (period_end >= period_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Immutable point-in-time report snapshots (SRS 15.12, audit GAP-039)';

CREATE INDEX idx_report_snapshots_lookup
    ON report_snapshots (report_type, period_start, period_end, department_id, time_zone);
